package Confirmation

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import HopGrp_Hops "grgrbll/fix/Shared/HopGrp_Hops"

import Parties_PartyIDs "grgrbll/fix/Shared/Parties_PartyIDs"

import OrdAllocGrp_Orders "grgrbll/fix/Shared/OrdAllocGrp_Orders"

import TrdRegTimestamps_TrdRegTimestamps "grgrbll/fix/Shared/TrdRegTimestamps_TrdRegTimestamps"

import SecAltIDGrp_SecurityAltID "grgrbll/fix/Shared/SecAltIDGrp_SecurityAltID"

import EvntGrp_Events "grgrbll/fix/Shared/EvntGrp_Events"

import InstrumentParties_InstrumentParties "grgrbll/fix/Shared/InstrumentParties_InstrumentParties"

import AttrbGrp_InstrAttrib "grgrbll/fix/Shared/AttrbGrp_InstrAttrib"

import UndInstrmtGrp_Underlyings "grgrbll/fix/Shared/UndInstrmtGrp_Underlyings"

import InstrmtLegGrp_Legs "grgrbll/fix/Shared/InstrmtLegGrp_Legs"

import CpctyConfGrp_Capacities "grgrbll/fix/Shared/CpctyConfGrp_Capacities"

import DlvyInstGrp_DlvyInst "grgrbll/fix/Shared/DlvyInstGrp_DlvyInst"

import Stipulations_Stipulations "grgrbll/fix/Shared/Stipulations_Stipulations"

import MiscFeesGrp_MiscFees "grgrbll/fix/Shared/MiscFeesGrp_MiscFees"


type confirmation_RegexValidator struct {
    BeginString *(regexp.Regexp)
    BodyLength *(regexp.Regexp)
    MsgType *(regexp.Regexp)
    SenderCompID *(regexp.Regexp)
    TargetCompID *(regexp.Regexp)
    OnBehalfOfCompID *(regexp.Regexp)
    DeliverToCompID *(regexp.Regexp)
    SecureDataLen *(regexp.Regexp)
    SecureData *(regexp.Regexp)
    MsgSeqNum *(regexp.Regexp)
    SenderSubID *(regexp.Regexp)
    SenderLocationID *(regexp.Regexp)
    TargetSubID *(regexp.Regexp)
    TargetLocationID *(regexp.Regexp)
    OnBehalfOfSubID *(regexp.Regexp)
    OnBehalfOfLocationID *(regexp.Regexp)
    DeliverToSubID *(regexp.Regexp)
    DeliverToLocationID *(regexp.Regexp)
    PossDupFlag *(regexp.Regexp)
    PossResend *(regexp.Regexp)
    SendingTime *(regexp.Regexp)
    OrigSendingTime *(regexp.Regexp)
    XmlDataLen *(regexp.Regexp)
    XmlData *(regexp.Regexp)
    MessageEncoding *(regexp.Regexp)
    LastMsgSeqNumProcessed *(regexp.Regexp)
    ApplVerID *(regexp.Regexp)
    CstmApplVerID *(regexp.Regexp)
    ConfirmID *(regexp.Regexp)
    ConfirmRefID *(regexp.Regexp)
    ConfirmReqID *(regexp.Regexp)
    ConfirmTransType *(regexp.Regexp)
    ConfirmType *(regexp.Regexp)
    CopyMsgIndicator *(regexp.Regexp)
    LegalConfirm *(regexp.Regexp)
    ConfirmStatus *(regexp.Regexp)
    AllocID *(regexp.Regexp)
    SecondaryAllocID *(regexp.Regexp)
    IndividualAllocID *(regexp.Regexp)
    TransactTime *(regexp.Regexp)
    TradeDate *(regexp.Regexp)
    Symbol *(regexp.Regexp)
    SymbolSfx *(regexp.Regexp)
    SecurityID *(regexp.Regexp)
    SecurityIDSource *(regexp.Regexp)
    Product *(regexp.Regexp)
    CFICode *(regexp.Regexp)
    SecurityType *(regexp.Regexp)
    SecuritySubType *(regexp.Regexp)
    MaturityMonthYear *(regexp.Regexp)
    MaturityDate *(regexp.Regexp)
    CouponPaymentDate *(regexp.Regexp)
    IssueDate *(regexp.Regexp)
    RepoCollateralSecurityType *(regexp.Regexp)
    RepurchaseTerm *(regexp.Regexp)
    RepurchaseRate *(regexp.Regexp)
    Factor *(regexp.Regexp)
    CreditRating *(regexp.Regexp)
    InstrRegistry *(regexp.Regexp)
    CountryOfIssue *(regexp.Regexp)
    StateOrProvinceOfIssue *(regexp.Regexp)
    LocaleOfIssue *(regexp.Regexp)
    RedemptionDate *(regexp.Regexp)
    StrikePrice *(regexp.Regexp)
    StrikeCurrency *(regexp.Regexp)
    OptAttribute *(regexp.Regexp)
    ContractMultiplier *(regexp.Regexp)
    CouponRate *(regexp.Regexp)
    SecurityExchange *(regexp.Regexp)
    Issuer *(regexp.Regexp)
    EncodedIssuerLen *(regexp.Regexp)
    EncodedIssuer *(regexp.Regexp)
    SecurityDesc *(regexp.Regexp)
    EncodedSecurityDescLen *(regexp.Regexp)
    EncodedSecurityDesc *(regexp.Regexp)
    Pool *(regexp.Regexp)
    ContractSettlMonth *(regexp.Regexp)
    CPProgram *(regexp.Regexp)
    CPRegType *(regexp.Regexp)
    DatedDate *(regexp.Regexp)
    InterestAccrualDate *(regexp.Regexp)
    SecurityStatus *(regexp.Regexp)
    SettleOnOpenFlag *(regexp.Regexp)
    InstrmtAssignmentMethod *(regexp.Regexp)
    StrikeMultiplier *(regexp.Regexp)
    StrikeValue *(regexp.Regexp)
    MinPriceIncrement *(regexp.Regexp)
    PositionLimit *(regexp.Regexp)
    NTPositionLimit *(regexp.Regexp)
    UnitofMeasure *(regexp.Regexp)
    TimeUnit *(regexp.Regexp)
    MaturityTime *(regexp.Regexp)
    DeliveryForm *(regexp.Regexp)
    PctAtRisk *(regexp.Regexp)
    AgreementDesc *(regexp.Regexp)
    AgreementID *(regexp.Regexp)
    AgreementDate *(regexp.Regexp)
    AgreementCurrency *(regexp.Regexp)
    TerminationType *(regexp.Regexp)
    StartDate *(regexp.Regexp)
    EndDate *(regexp.Regexp)
    DeliveryType *(regexp.Regexp)
    MarginRatio *(regexp.Regexp)
    YieldType *(regexp.Regexp)
    Yield *(regexp.Regexp)
    YieldCalcDate *(regexp.Regexp)
    YieldRedemptionDate *(regexp.Regexp)
    YieldRedemptionPrice *(regexp.Regexp)
    YieldRedemptionPriceType *(regexp.Regexp)
    AllocQty *(regexp.Regexp)
    QtyType *(regexp.Regexp)
    Side *(regexp.Regexp)
    Currency *(regexp.Regexp)
    LastMkt *(regexp.Regexp)
    AllocAccount *(regexp.Regexp)
    AllocAcctIDSource *(regexp.Regexp)
    AllocAccountType *(regexp.Regexp)
    AvgPx *(regexp.Regexp)
    AvgPxPrecision *(regexp.Regexp)
    PriceType *(regexp.Regexp)
    AvgParPx *(regexp.Regexp)
    Spread *(regexp.Regexp)
    BenchmarkCurveCurrency *(regexp.Regexp)
    BenchmarkCurveName *(regexp.Regexp)
    BenchmarkCurvePoint *(regexp.Regexp)
    BenchmarkPrice *(regexp.Regexp)
    BenchmarkPriceType *(regexp.Regexp)
    BenchmarkSecurityID *(regexp.Regexp)
    BenchmarkSecurityIDSource *(regexp.Regexp)
    ReportedPx *(regexp.Regexp)
    Text *(regexp.Regexp)
    EncodedTextLen *(regexp.Regexp)
    EncodedText *(regexp.Regexp)
    ProcessCode *(regexp.Regexp)
    GrossTradeAmt *(regexp.Regexp)
    NumDaysInterest *(regexp.Regexp)
    ExDate *(regexp.Regexp)
    AccruedInterestRate *(regexp.Regexp)
    AccruedInterestAmt *(regexp.Regexp)
    InterestAtMaturity *(regexp.Regexp)
    EndAccruedInterestAmt *(regexp.Regexp)
    StartCash *(regexp.Regexp)
    EndCash *(regexp.Regexp)
    Concession *(regexp.Regexp)
    TotalTakedown *(regexp.Regexp)
    NetMoney *(regexp.Regexp)
    MaturityNetMoney *(regexp.Regexp)
    SettlCurrAmt *(regexp.Regexp)
    SettlCurrency *(regexp.Regexp)
    SettlCurrFxRate *(regexp.Regexp)
    SettlCurrFxRateCalc *(regexp.Regexp)
    SettlType *(regexp.Regexp)
    SettlDate *(regexp.Regexp)
    SettlDeliveryType *(regexp.Regexp)
    StandInstDbType *(regexp.Regexp)
    StandInstDbName *(regexp.Regexp)
    StandInstDbID *(regexp.Regexp)
    Commission *(regexp.Regexp)
    CommType *(regexp.Regexp)
    CommCurrency *(regexp.Regexp)
    FundRenewWaiv *(regexp.Regexp)
    SharedCommission *(regexp.Regexp)
    SignatureLength *(regexp.Regexp)
    Signature *(regexp.Regexp)
    CheckSum *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myConfirmation_RegexValidator confirmation_RegexValidator

func init() {
    myConfirmation_RegexValidator
    myConfirmation_RegexValidator.BeginString = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.BodyLength = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.MsgType = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SenderCompID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.TargetCompID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.OnBehalfOfCompID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.DeliverToCompID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SecureDataLen = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.SecureData = regexp.MustCompile(`.*`)
    myConfirmation_RegexValidator.MsgSeqNum = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.SenderSubID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SenderLocationID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.TargetSubID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.TargetLocationID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.OnBehalfOfSubID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.OnBehalfOfLocationID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.DeliverToSubID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.DeliverToLocationID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.PossDupFlag = regexp.MustCompile(`[YN]`)
    myConfirmation_RegexValidator.PossResend = regexp.MustCompile(`[YN]`)
    myConfirmation_RegexValidator.SendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myConfirmation_RegexValidator.OrigSendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myConfirmation_RegexValidator.XmlDataLen = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.XmlData = regexp.MustCompile(`.*`)
    myConfirmation_RegexValidator.MessageEncoding = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.LastMsgSeqNumProcessed = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.ApplVerID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.CstmApplVerID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.ConfirmID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.ConfirmRefID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.ConfirmReqID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.ConfirmTransType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.ConfirmType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.CopyMsgIndicator = regexp.MustCompile(`[YN]`)
    myConfirmation_RegexValidator.LegalConfirm = regexp.MustCompile(`[YN]`)
    myConfirmation_RegexValidator.ConfirmStatus = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.AllocID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SecondaryAllocID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.IndividualAllocID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.TransactTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myConfirmation_RegexValidator.TradeDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.Symbol = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SymbolSfx = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SecurityID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SecurityIDSource = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.Product = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.CFICode = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SecurityType = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SecuritySubType = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.MaturityMonthYear = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myConfirmation_RegexValidator.MaturityDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.CouponPaymentDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.IssueDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.RepoCollateralSecurityType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.RepurchaseTerm = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.RepurchaseRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.Factor = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.CreditRating = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.InstrRegistry = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.CountryOfIssue = regexp.MustCompile(`[A-Z]{2}`)
    myConfirmation_RegexValidator.StateOrProvinceOfIssue = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.LocaleOfIssue = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.RedemptionDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.StrikePrice = regexp.MustCompile(``)
    myConfirmation_RegexValidator.StrikeCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myConfirmation_RegexValidator.OptAttribute = regexp.MustCompile(`[^|]`)
    myConfirmation_RegexValidator.ContractMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.CouponRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.SecurityExchange = regexp.MustCompile(`[A-Z0-9]{4}`)
    myConfirmation_RegexValidator.Issuer = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.EncodedIssuerLen = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.EncodedIssuer = regexp.MustCompile(`.*`)
    myConfirmation_RegexValidator.SecurityDesc = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.EncodedSecurityDescLen = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.EncodedSecurityDesc = regexp.MustCompile(`.*`)
    myConfirmation_RegexValidator.Pool = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.ContractSettlMonth = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myConfirmation_RegexValidator.CPProgram = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.CPRegType = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.DatedDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.InterestAccrualDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.SecurityStatus = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SettleOnOpenFlag = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.InstrmtAssignmentMethod = regexp.MustCompile(`[^|]`)
    myConfirmation_RegexValidator.StrikeMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.StrikeValue = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.MinPriceIncrement = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.PositionLimit = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.NTPositionLimit = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.UnitofMeasure = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.TimeUnit = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.MaturityTime = regexp.MustCompile(`\d{2}:\d{2}(:\d{2})?(Z|[\+-]\d{2}(:\d{2})?)`)
    myConfirmation_RegexValidator.DeliveryForm = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.PctAtRisk = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.AgreementDesc = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.AgreementID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.AgreementDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.AgreementCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myConfirmation_RegexValidator.TerminationType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.StartDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.EndDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.DeliveryType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.MarginRatio = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.YieldType = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.Yield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.YieldCalcDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.YieldRedemptionDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.YieldRedemptionPrice = regexp.MustCompile(``)
    myConfirmation_RegexValidator.YieldRedemptionPriceType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.AllocQty = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.QtyType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.Side = regexp.MustCompile(`[^|]`)
    myConfirmation_RegexValidator.Currency = regexp.MustCompile(`[A-Z]{3}`)
    myConfirmation_RegexValidator.LastMkt = regexp.MustCompile(`[A-Z0-9]{4}`)
    myConfirmation_RegexValidator.AllocAccount = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.AllocAcctIDSource = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.AllocAccountType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.AvgPx = regexp.MustCompile(``)
    myConfirmation_RegexValidator.AvgPxPrecision = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.PriceType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.AvgParPx = regexp.MustCompile(``)
    myConfirmation_RegexValidator.Spread = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.BenchmarkCurveCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myConfirmation_RegexValidator.BenchmarkCurveName = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.BenchmarkCurvePoint = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.BenchmarkPrice = regexp.MustCompile(``)
    myConfirmation_RegexValidator.BenchmarkPriceType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.BenchmarkSecurityID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.BenchmarkSecurityIDSource = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.ReportedPx = regexp.MustCompile(``)
    myConfirmation_RegexValidator.Text = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.EncodedTextLen = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.EncodedText = regexp.MustCompile(`.*`)
    myConfirmation_RegexValidator.ProcessCode = regexp.MustCompile(`[^|]`)
    myConfirmation_RegexValidator.GrossTradeAmt = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.NumDaysInterest = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.ExDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.AccruedInterestRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.AccruedInterestAmt = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.InterestAtMaturity = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.EndAccruedInterestAmt = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.StartCash = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.EndCash = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.Concession = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.TotalTakedown = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.NetMoney = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.MaturityNetMoney = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.SettlCurrAmt = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.SettlCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myConfirmation_RegexValidator.SettlCurrFxRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.SettlCurrFxRateCalc = regexp.MustCompile(`[^|]`)
    myConfirmation_RegexValidator.SettlType = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.SettlDate = regexp.MustCompile(`[0-9]{8}`)
    myConfirmation_RegexValidator.SettlDeliveryType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.StandInstDbType = regexp.MustCompile(`-?\d+`)
    myConfirmation_RegexValidator.StandInstDbName = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.StandInstDbID = regexp.MustCompile(`[^|]*`)
    myConfirmation_RegexValidator.Commission = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.CommType = regexp.MustCompile(`[^|]`)
    myConfirmation_RegexValidator.CommCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myConfirmation_RegexValidator.FundRenewWaiv = regexp.MustCompile(`[^|]`)
    myConfirmation_RegexValidator.SharedCommission = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myConfirmation_RegexValidator.SignatureLength = regexp.MustCompile(`\d+`)
    myConfirmation_RegexValidator.Signature = regexp.MustCompile(`.*`)
    myConfirmation_RegexValidator.CheckSum = regexp.MustCompile(`[^|]*`)
}



func (m *Confirmation) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.BeginString.HasValue()
    
    
    
    valid = valid && m.BodyLength.HasValue()
    
    
    
    valid = valid && m.MsgType.HasValue()
    
    
    
    valid = valid && m.SenderCompID.HasValue()
    
    
    
    valid = valid && m.TargetCompID.HasValue()
    
    
    
    valid = valid && m.MsgSeqNum.HasValue()
    
    
    
    valid = valid && m.SendingTime.HasValue()
    
    
    
    for _, g := range(m.Hops) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.ConfirmID.HasValue()
    
    
    
    valid = valid && m.ConfirmTransType.HasValue()
    
    
    
    valid = valid && m.ConfirmType.HasValue()
    
    
    
    valid = valid && m.ConfirmStatus.HasValue()
    
    
    
    for _, g := range(m.PartyIDs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Orders) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.TransactTime.HasValue()
    
    
    
    valid = valid && m.TradeDate.HasValue()
    
    
    
    for _, g := range(m.TrdRegTimestamps) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.SecurityAltID) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Events) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.InstrumentParties) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.InstrAttrib) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Underlyings) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Legs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.AllocQty.HasValue()
    
    
    
    valid = valid && m.Side.HasValue()
    
    
    
    for _, g := range(m.Capacities) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.AllocAccount.HasValue()
    
    
    
    valid = valid && m.AvgPx.HasValue()
    
    
    
    valid = valid && m.GrossTradeAmt.HasValue()
    
    
    
    valid = valid && m.NetMoney.HasValue()
    
    
    
    for _, g := range(m.DlvyInst) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Stipulations) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.MiscFees) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.CheckSum.HasValue()
    
    
    
    
    
    return valid
}




