package CrossOrderCancelRequest

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import HopGrp_Hops "grgrbll/fix/Shared/HopGrp_Hops"

import SideCrossOrdCxlGrp_Sides "grgrbll/fix/Shared/SideCrossOrdCxlGrp_Sides"

import SecAltIDGrp_SecurityAltID "grgrbll/fix/Shared/SecAltIDGrp_SecurityAltID"

import EvntGrp_Events "grgrbll/fix/Shared/EvntGrp_Events"

import InstrumentParties_InstrumentParties "grgrbll/fix/Shared/InstrumentParties_InstrumentParties"

import UndInstrmtGrp_Underlyings "grgrbll/fix/Shared/UndInstrmtGrp_Underlyings"

import InstrmtLegGrp_Legs "grgrbll/fix/Shared/InstrmtLegGrp_Legs"

import RootParties_RootPartyIDs "grgrbll/fix/Shared/RootParties_RootPartyIDs"


type crossOrderCancelRequest_RegexValidator struct {
    BeginString *(regexp.Regexp)
    BodyLength *(regexp.Regexp)
    MsgType *(regexp.Regexp)
    SenderCompID *(regexp.Regexp)
    TargetCompID *(regexp.Regexp)
    OnBehalfOfCompID *(regexp.Regexp)
    DeliverToCompID *(regexp.Regexp)
    SecureDataLen *(regexp.Regexp)
    SecureData *(regexp.Regexp)
    MsgSeqNum *(regexp.Regexp)
    SenderSubID *(regexp.Regexp)
    SenderLocationID *(regexp.Regexp)
    TargetSubID *(regexp.Regexp)
    TargetLocationID *(regexp.Regexp)
    OnBehalfOfSubID *(regexp.Regexp)
    OnBehalfOfLocationID *(regexp.Regexp)
    DeliverToSubID *(regexp.Regexp)
    DeliverToLocationID *(regexp.Regexp)
    PossDupFlag *(regexp.Regexp)
    PossResend *(regexp.Regexp)
    SendingTime *(regexp.Regexp)
    OrigSendingTime *(regexp.Regexp)
    XmlDataLen *(regexp.Regexp)
    XmlData *(regexp.Regexp)
    MessageEncoding *(regexp.Regexp)
    LastMsgSeqNumProcessed *(regexp.Regexp)
    ApplVerID *(regexp.Regexp)
    CstmApplVerID *(regexp.Regexp)
    OrderID *(regexp.Regexp)
    CrossID *(regexp.Regexp)
    OrigCrossID *(regexp.Regexp)
    CrossType *(regexp.Regexp)
    CrossPrioritization *(regexp.Regexp)
    Symbol *(regexp.Regexp)
    SymbolSfx *(regexp.Regexp)
    SecurityID *(regexp.Regexp)
    SecurityIDSource *(regexp.Regexp)
    Product *(regexp.Regexp)
    CFICode *(regexp.Regexp)
    SecurityType *(regexp.Regexp)
    SecuritySubType *(regexp.Regexp)
    MaturityMonthYear *(regexp.Regexp)
    MaturityDate *(regexp.Regexp)
    CouponPaymentDate *(regexp.Regexp)
    IssueDate *(regexp.Regexp)
    RepoCollateralSecurityType *(regexp.Regexp)
    RepurchaseTerm *(regexp.Regexp)
    RepurchaseRate *(regexp.Regexp)
    Factor *(regexp.Regexp)
    CreditRating *(regexp.Regexp)
    InstrRegistry *(regexp.Regexp)
    CountryOfIssue *(regexp.Regexp)
    StateOrProvinceOfIssue *(regexp.Regexp)
    LocaleOfIssue *(regexp.Regexp)
    RedemptionDate *(regexp.Regexp)
    StrikePrice *(regexp.Regexp)
    StrikeCurrency *(regexp.Regexp)
    OptAttribute *(regexp.Regexp)
    ContractMultiplier *(regexp.Regexp)
    CouponRate *(regexp.Regexp)
    SecurityExchange *(regexp.Regexp)
    Issuer *(regexp.Regexp)
    EncodedIssuerLen *(regexp.Regexp)
    EncodedIssuer *(regexp.Regexp)
    SecurityDesc *(regexp.Regexp)
    EncodedSecurityDescLen *(regexp.Regexp)
    EncodedSecurityDesc *(regexp.Regexp)
    Pool *(regexp.Regexp)
    ContractSettlMonth *(regexp.Regexp)
    CPProgram *(regexp.Regexp)
    CPRegType *(regexp.Regexp)
    DatedDate *(regexp.Regexp)
    InterestAccrualDate *(regexp.Regexp)
    SecurityStatus *(regexp.Regexp)
    SettleOnOpenFlag *(regexp.Regexp)
    InstrmtAssignmentMethod *(regexp.Regexp)
    StrikeMultiplier *(regexp.Regexp)
    StrikeValue *(regexp.Regexp)
    MinPriceIncrement *(regexp.Regexp)
    PositionLimit *(regexp.Regexp)
    NTPositionLimit *(regexp.Regexp)
    UnitofMeasure *(regexp.Regexp)
    TimeUnit *(regexp.Regexp)
    MaturityTime *(regexp.Regexp)
    TransactTime *(regexp.Regexp)
    HostCrossID *(regexp.Regexp)
    SignatureLength *(regexp.Regexp)
    Signature *(regexp.Regexp)
    CheckSum *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myCrossOrderCancelRequest_RegexValidator crossOrderCancelRequest_RegexValidator

func init() {
    myCrossOrderCancelRequest_RegexValidator
    myCrossOrderCancelRequest_RegexValidator.BeginString = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.BodyLength = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.MsgType = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SenderCompID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.TargetCompID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.OnBehalfOfCompID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.DeliverToCompID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SecureDataLen = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.SecureData = regexp.MustCompile(`.*`)
    myCrossOrderCancelRequest_RegexValidator.MsgSeqNum = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.SenderSubID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SenderLocationID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.TargetSubID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.TargetLocationID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.OnBehalfOfSubID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.OnBehalfOfLocationID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.DeliverToSubID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.DeliverToLocationID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.PossDupFlag = regexp.MustCompile(`[YN]`)
    myCrossOrderCancelRequest_RegexValidator.PossResend = regexp.MustCompile(`[YN]`)
    myCrossOrderCancelRequest_RegexValidator.SendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myCrossOrderCancelRequest_RegexValidator.OrigSendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myCrossOrderCancelRequest_RegexValidator.XmlDataLen = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.XmlData = regexp.MustCompile(`.*`)
    myCrossOrderCancelRequest_RegexValidator.MessageEncoding = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.LastMsgSeqNumProcessed = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.ApplVerID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.CstmApplVerID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.OrderID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.CrossID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.OrigCrossID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.CrossType = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.CrossPrioritization = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.Symbol = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SymbolSfx = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SecurityID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SecurityIDSource = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.Product = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.CFICode = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SecurityType = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SecuritySubType = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.MaturityMonthYear = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myCrossOrderCancelRequest_RegexValidator.MaturityDate = regexp.MustCompile(`[0-9]{8}`)
    myCrossOrderCancelRequest_RegexValidator.CouponPaymentDate = regexp.MustCompile(`[0-9]{8}`)
    myCrossOrderCancelRequest_RegexValidator.IssueDate = regexp.MustCompile(`[0-9]{8}`)
    myCrossOrderCancelRequest_RegexValidator.RepoCollateralSecurityType = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.RepurchaseTerm = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.RepurchaseRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myCrossOrderCancelRequest_RegexValidator.Factor = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myCrossOrderCancelRequest_RegexValidator.CreditRating = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.InstrRegistry = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.CountryOfIssue = regexp.MustCompile(`[A-Z]{2}`)
    myCrossOrderCancelRequest_RegexValidator.StateOrProvinceOfIssue = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.LocaleOfIssue = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.RedemptionDate = regexp.MustCompile(`[0-9]{8}`)
    myCrossOrderCancelRequest_RegexValidator.StrikePrice = regexp.MustCompile(``)
    myCrossOrderCancelRequest_RegexValidator.StrikeCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myCrossOrderCancelRequest_RegexValidator.OptAttribute = regexp.MustCompile(`[^|]`)
    myCrossOrderCancelRequest_RegexValidator.ContractMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myCrossOrderCancelRequest_RegexValidator.CouponRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myCrossOrderCancelRequest_RegexValidator.SecurityExchange = regexp.MustCompile(`[A-Z0-9]{4}`)
    myCrossOrderCancelRequest_RegexValidator.Issuer = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.EncodedIssuerLen = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.EncodedIssuer = regexp.MustCompile(`.*`)
    myCrossOrderCancelRequest_RegexValidator.SecurityDesc = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.EncodedSecurityDescLen = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.EncodedSecurityDesc = regexp.MustCompile(`.*`)
    myCrossOrderCancelRequest_RegexValidator.Pool = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.ContractSettlMonth = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myCrossOrderCancelRequest_RegexValidator.CPProgram = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.CPRegType = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.DatedDate = regexp.MustCompile(`[0-9]{8}`)
    myCrossOrderCancelRequest_RegexValidator.InterestAccrualDate = regexp.MustCompile(`[0-9]{8}`)
    myCrossOrderCancelRequest_RegexValidator.SecurityStatus = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SettleOnOpenFlag = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.InstrmtAssignmentMethod = regexp.MustCompile(`[^|]`)
    myCrossOrderCancelRequest_RegexValidator.StrikeMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myCrossOrderCancelRequest_RegexValidator.StrikeValue = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myCrossOrderCancelRequest_RegexValidator.MinPriceIncrement = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myCrossOrderCancelRequest_RegexValidator.PositionLimit = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.NTPositionLimit = regexp.MustCompile(`-?\d+`)
    myCrossOrderCancelRequest_RegexValidator.UnitofMeasure = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.TimeUnit = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.MaturityTime = regexp.MustCompile(`\d{2}:\d{2}(:\d{2})?(Z|[\+-]\d{2}(:\d{2})?)`)
    myCrossOrderCancelRequest_RegexValidator.TransactTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myCrossOrderCancelRequest_RegexValidator.HostCrossID = regexp.MustCompile(`[^|]*`)
    myCrossOrderCancelRequest_RegexValidator.SignatureLength = regexp.MustCompile(`\d+`)
    myCrossOrderCancelRequest_RegexValidator.Signature = regexp.MustCompile(`.*`)
    myCrossOrderCancelRequest_RegexValidator.CheckSum = regexp.MustCompile(`[^|]*`)
}



func (m *CrossOrderCancelRequest) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.BeginString.HasValue()
    
    
    
    valid = valid && m.BodyLength.HasValue()
    
    
    
    valid = valid && m.MsgType.HasValue()
    
    
    
    valid = valid && m.SenderCompID.HasValue()
    
    
    
    valid = valid && m.TargetCompID.HasValue()
    
    
    
    valid = valid && m.MsgSeqNum.HasValue()
    
    
    
    valid = valid && m.SendingTime.HasValue()
    
    
    
    for _, g := range(m.Hops) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.CrossID.HasValue()
    
    
    
    valid = valid && m.OrigCrossID.HasValue()
    
    
    
    valid = valid && m.CrossType.HasValue()
    
    
    
    valid = valid && m.CrossPrioritization.HasValue()
    
    
    
    for _, g := range(m.Sides) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.SecurityAltID) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Events) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.InstrumentParties) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Underlyings) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Legs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.TransactTime.HasValue()
    
    
    
    for _, g := range(m.RootPartyIDs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.CheckSum.HasValue()
    
    
    
    
    
    return valid
}




