package NestedParties2_Nested2PartyIDs

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit



import NstdPtys2SubGrp_Nested2PartySubIDs "grgrbll/fix/Shared/NstdPtys2SubGrp_Nested2PartySubIDs"


type NestedParties2_Nested2PartyIDs struct {
    Nested2PartyID Types.String `id:"757", required:"N" `
    Nested2PartyIDSource Types.Char `id:"758", required:"N" `
    Nested2PartyRole Types.Int `id:"759", required:"N" `
    Nested2PartySubIDs []NstdPtys2SubGrp_Nested2PartySubIDs.NstdPtys2SubGrp_Nested2PartySubIDs `counter_name:"NoNested2PartySubIDs", counter_id:"806"`
    _controlBlock fixMessageControlBlock
}
