package NestedParties_NestedPartyIDs

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import NstdPtysSubGrp_NestedPartySubIDs "grgrbll/fix/Shared/NstdPtysSubGrp_NestedPartySubIDs"


type nestedParties_NestedPartyIDs_RegexValidator struct {
    NestedPartyID *(regexp.Regexp)
    NestedPartyIDSource *(regexp.Regexp)
    NestedPartyRole *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myNestedParties_NestedPartyIDs_RegexValidator nestedParties_NestedPartyIDs_RegexValidator

func init() {
    myNestedParties_NestedPartyIDs_RegexValidator
    myNestedParties_NestedPartyIDs_RegexValidator.NestedPartyID = regexp.MustCompile(`[^|]*`)
    myNestedParties_NestedPartyIDs_RegexValidator.NestedPartyIDSource = regexp.MustCompile(`[^|]`)
    myNestedParties_NestedPartyIDs_RegexValidator.NestedPartyRole = regexp.MustCompile(`-?\d+`)
}



func (m *NestedParties_NestedPartyIDs) HasRequiredFields() bool {
    valid := true
    
    

    
    
    for _, g := range(m.NestedPartySubIDs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    
    
    return valid
}




