package NestedParties_NestedPartyIDs

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit



import NstdPtysSubGrp_NestedPartySubIDs "grgrbll/fix/Shared/NstdPtysSubGrp_NestedPartySubIDs"


type NestedParties_NestedPartyIDs struct {
    NestedPartyID Types.String `id:"524", required:"N" `
    NestedPartyIDSource Types.Char `id:"525", required:"N" `
    NestedPartyRole Types.Int `id:"538", required:"N" `
    NestedPartySubIDs []NstdPtysSubGrp_NestedPartySubIDs.NstdPtysSubGrp_NestedPartySubIDs `counter_name:"NoNestedPartySubIDs", counter_id:"804"`
    _controlBlock fixMessageControlBlock
}
