package QuoteResponse

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import HopGrp_Hops "grgrbll/fix/Shared/HopGrp_Hops"

import QuotQualGrp_QuoteQualifiers "grgrbll/fix/Shared/QuotQualGrp_QuoteQualifiers"

import Parties_PartyIDs "grgrbll/fix/Shared/Parties_PartyIDs"

import SecAltIDGrp_SecurityAltID "grgrbll/fix/Shared/SecAltIDGrp_SecurityAltID"

import EvntGrp_Events "grgrbll/fix/Shared/EvntGrp_Events"

import InstrumentParties_InstrumentParties "grgrbll/fix/Shared/InstrumentParties_InstrumentParties"

import UndInstrmtGrp_Underlyings "grgrbll/fix/Shared/UndInstrmtGrp_Underlyings"

import Stipulations_Stipulations "grgrbll/fix/Shared/Stipulations_Stipulations"

import LegQuotGrp_Legs "grgrbll/fix/Shared/LegQuotGrp_Legs"


type quoteResponse_RegexValidator struct {
    BeginString *(regexp.Regexp)
    BodyLength *(regexp.Regexp)
    MsgType *(regexp.Regexp)
    SenderCompID *(regexp.Regexp)
    TargetCompID *(regexp.Regexp)
    OnBehalfOfCompID *(regexp.Regexp)
    DeliverToCompID *(regexp.Regexp)
    SecureDataLen *(regexp.Regexp)
    SecureData *(regexp.Regexp)
    MsgSeqNum *(regexp.Regexp)
    SenderSubID *(regexp.Regexp)
    SenderLocationID *(regexp.Regexp)
    TargetSubID *(regexp.Regexp)
    TargetLocationID *(regexp.Regexp)
    OnBehalfOfSubID *(regexp.Regexp)
    OnBehalfOfLocationID *(regexp.Regexp)
    DeliverToSubID *(regexp.Regexp)
    DeliverToLocationID *(regexp.Regexp)
    PossDupFlag *(regexp.Regexp)
    PossResend *(regexp.Regexp)
    SendingTime *(regexp.Regexp)
    OrigSendingTime *(regexp.Regexp)
    XmlDataLen *(regexp.Regexp)
    XmlData *(regexp.Regexp)
    MessageEncoding *(regexp.Regexp)
    LastMsgSeqNumProcessed *(regexp.Regexp)
    ApplVerID *(regexp.Regexp)
    CstmApplVerID *(regexp.Regexp)
    QuoteRespID *(regexp.Regexp)
    QuoteID *(regexp.Regexp)
    QuoteRespType *(regexp.Regexp)
    ClOrdID *(regexp.Regexp)
    OrderCapacity *(regexp.Regexp)
    IOIID *(regexp.Regexp)
    QuoteType *(regexp.Regexp)
    TradingSessionID *(regexp.Regexp)
    TradingSessionSubID *(regexp.Regexp)
    Symbol *(regexp.Regexp)
    SymbolSfx *(regexp.Regexp)
    SecurityID *(regexp.Regexp)
    SecurityIDSource *(regexp.Regexp)
    Product *(regexp.Regexp)
    CFICode *(regexp.Regexp)
    SecurityType *(regexp.Regexp)
    SecuritySubType *(regexp.Regexp)
    MaturityMonthYear *(regexp.Regexp)
    MaturityDate *(regexp.Regexp)
    CouponPaymentDate *(regexp.Regexp)
    IssueDate *(regexp.Regexp)
    RepoCollateralSecurityType *(regexp.Regexp)
    RepurchaseTerm *(regexp.Regexp)
    RepurchaseRate *(regexp.Regexp)
    Factor *(regexp.Regexp)
    CreditRating *(regexp.Regexp)
    InstrRegistry *(regexp.Regexp)
    CountryOfIssue *(regexp.Regexp)
    StateOrProvinceOfIssue *(regexp.Regexp)
    LocaleOfIssue *(regexp.Regexp)
    RedemptionDate *(regexp.Regexp)
    StrikePrice *(regexp.Regexp)
    StrikeCurrency *(regexp.Regexp)
    OptAttribute *(regexp.Regexp)
    ContractMultiplier *(regexp.Regexp)
    CouponRate *(regexp.Regexp)
    SecurityExchange *(regexp.Regexp)
    Issuer *(regexp.Regexp)
    EncodedIssuerLen *(regexp.Regexp)
    EncodedIssuer *(regexp.Regexp)
    SecurityDesc *(regexp.Regexp)
    EncodedSecurityDescLen *(regexp.Regexp)
    EncodedSecurityDesc *(regexp.Regexp)
    Pool *(regexp.Regexp)
    ContractSettlMonth *(regexp.Regexp)
    CPProgram *(regexp.Regexp)
    CPRegType *(regexp.Regexp)
    DatedDate *(regexp.Regexp)
    InterestAccrualDate *(regexp.Regexp)
    SecurityStatus *(regexp.Regexp)
    SettleOnOpenFlag *(regexp.Regexp)
    InstrmtAssignmentMethod *(regexp.Regexp)
    StrikeMultiplier *(regexp.Regexp)
    StrikeValue *(regexp.Regexp)
    MinPriceIncrement *(regexp.Regexp)
    PositionLimit *(regexp.Regexp)
    NTPositionLimit *(regexp.Regexp)
    UnitofMeasure *(regexp.Regexp)
    TimeUnit *(regexp.Regexp)
    MaturityTime *(regexp.Regexp)
    AgreementDesc *(regexp.Regexp)
    AgreementID *(regexp.Regexp)
    AgreementDate *(regexp.Regexp)
    AgreementCurrency *(regexp.Regexp)
    TerminationType *(regexp.Regexp)
    StartDate *(regexp.Regexp)
    EndDate *(regexp.Regexp)
    DeliveryType *(regexp.Regexp)
    MarginRatio *(regexp.Regexp)
    Side *(regexp.Regexp)
    OrderQty *(regexp.Regexp)
    CashOrderQty *(regexp.Regexp)
    OrderPercent *(regexp.Regexp)
    RoundingDirection *(regexp.Regexp)
    RoundingModulus *(regexp.Regexp)
    SettlType *(regexp.Regexp)
    SettlDate *(regexp.Regexp)
    SettlDate2 *(regexp.Regexp)
    OrderQty2 *(regexp.Regexp)
    Currency *(regexp.Regexp)
    Account *(regexp.Regexp)
    AcctIDSource *(regexp.Regexp)
    AccountType *(regexp.Regexp)
    BidPx *(regexp.Regexp)
    OfferPx *(regexp.Regexp)
    MktBidPx *(regexp.Regexp)
    MktOfferPx *(regexp.Regexp)
    MinBidSize *(regexp.Regexp)
    BidSize *(regexp.Regexp)
    MinOfferSize *(regexp.Regexp)
    OfferSize *(regexp.Regexp)
    ValidUntilTime *(regexp.Regexp)
    BidSpotRate *(regexp.Regexp)
    OfferSpotRate *(regexp.Regexp)
    BidForwardPoints *(regexp.Regexp)
    OfferForwardPoints *(regexp.Regexp)
    MidPx *(regexp.Regexp)
    BidYield *(regexp.Regexp)
    MidYield *(regexp.Regexp)
    OfferYield *(regexp.Regexp)
    TransactTime *(regexp.Regexp)
    OrdType *(regexp.Regexp)
    BidForwardPoints2 *(regexp.Regexp)
    OfferForwardPoints2 *(regexp.Regexp)
    SettlCurrBidFxRate *(regexp.Regexp)
    SettlCurrOfferFxRate *(regexp.Regexp)
    SettlCurrFxRateCalc *(regexp.Regexp)
    Commission *(regexp.Regexp)
    CommType *(regexp.Regexp)
    CustOrderCapacity *(regexp.Regexp)
    ExDestination *(regexp.Regexp)
    Text *(regexp.Regexp)
    EncodedTextLen *(regexp.Regexp)
    EncodedText *(regexp.Regexp)
    Price *(regexp.Regexp)
    PriceType *(regexp.Regexp)
    Spread *(regexp.Regexp)
    BenchmarkCurveCurrency *(regexp.Regexp)
    BenchmarkCurveName *(regexp.Regexp)
    BenchmarkCurvePoint *(regexp.Regexp)
    BenchmarkPrice *(regexp.Regexp)
    BenchmarkPriceType *(regexp.Regexp)
    BenchmarkSecurityID *(regexp.Regexp)
    BenchmarkSecurityIDSource *(regexp.Regexp)
    YieldType *(regexp.Regexp)
    Yield *(regexp.Regexp)
    YieldCalcDate *(regexp.Regexp)
    YieldRedemptionDate *(regexp.Regexp)
    YieldRedemptionPrice *(regexp.Regexp)
    YieldRedemptionPriceType *(regexp.Regexp)
    ExDestinationIDSource *(regexp.Regexp)
    SignatureLength *(regexp.Regexp)
    Signature *(regexp.Regexp)
    CheckSum *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myQuoteResponse_RegexValidator quoteResponse_RegexValidator

func init() {
    myQuoteResponse_RegexValidator
    myQuoteResponse_RegexValidator.BeginString = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.BodyLength = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.MsgType = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SenderCompID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.TargetCompID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.OnBehalfOfCompID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.DeliverToCompID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SecureDataLen = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.SecureData = regexp.MustCompile(`.*`)
    myQuoteResponse_RegexValidator.MsgSeqNum = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.SenderSubID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SenderLocationID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.TargetSubID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.TargetLocationID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.OnBehalfOfSubID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.OnBehalfOfLocationID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.DeliverToSubID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.DeliverToLocationID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.PossDupFlag = regexp.MustCompile(`[YN]`)
    myQuoteResponse_RegexValidator.PossResend = regexp.MustCompile(`[YN]`)
    myQuoteResponse_RegexValidator.SendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myQuoteResponse_RegexValidator.OrigSendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myQuoteResponse_RegexValidator.XmlDataLen = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.XmlData = regexp.MustCompile(`.*`)
    myQuoteResponse_RegexValidator.MessageEncoding = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.LastMsgSeqNumProcessed = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.ApplVerID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.CstmApplVerID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.QuoteRespID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.QuoteID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.QuoteRespType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.ClOrdID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.OrderCapacity = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.IOIID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.QuoteType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.TradingSessionID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.TradingSessionSubID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.Symbol = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SymbolSfx = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SecurityID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SecurityIDSource = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.Product = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.CFICode = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SecurityType = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SecuritySubType = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.MaturityMonthYear = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myQuoteResponse_RegexValidator.MaturityDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.CouponPaymentDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.IssueDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.RepoCollateralSecurityType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.RepurchaseTerm = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.RepurchaseRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.Factor = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.CreditRating = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.InstrRegistry = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.CountryOfIssue = regexp.MustCompile(`[A-Z]{2}`)
    myQuoteResponse_RegexValidator.StateOrProvinceOfIssue = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.LocaleOfIssue = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.RedemptionDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.StrikePrice = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.StrikeCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myQuoteResponse_RegexValidator.OptAttribute = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.ContractMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.CouponRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.SecurityExchange = regexp.MustCompile(`[A-Z0-9]{4}`)
    myQuoteResponse_RegexValidator.Issuer = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.EncodedIssuerLen = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.EncodedIssuer = regexp.MustCompile(`.*`)
    myQuoteResponse_RegexValidator.SecurityDesc = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.EncodedSecurityDescLen = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.EncodedSecurityDesc = regexp.MustCompile(`.*`)
    myQuoteResponse_RegexValidator.Pool = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.ContractSettlMonth = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myQuoteResponse_RegexValidator.CPProgram = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.CPRegType = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.DatedDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.InterestAccrualDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.SecurityStatus = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SettleOnOpenFlag = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.InstrmtAssignmentMethod = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.StrikeMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.StrikeValue = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.MinPriceIncrement = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.PositionLimit = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.NTPositionLimit = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.UnitofMeasure = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.TimeUnit = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.MaturityTime = regexp.MustCompile(`\d{2}:\d{2}(:\d{2})?(Z|[\+-]\d{2}(:\d{2})?)`)
    myQuoteResponse_RegexValidator.AgreementDesc = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.AgreementID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.AgreementDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.AgreementCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myQuoteResponse_RegexValidator.TerminationType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.StartDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.EndDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.DeliveryType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.MarginRatio = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.Side = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.OrderQty = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.CashOrderQty = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.OrderPercent = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.RoundingDirection = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.RoundingModulus = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.SettlType = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.SettlDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.SettlDate2 = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.OrderQty2 = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.Currency = regexp.MustCompile(`[A-Z]{3}`)
    myQuoteResponse_RegexValidator.Account = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.AcctIDSource = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.AccountType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.BidPx = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.OfferPx = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.MktBidPx = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.MktOfferPx = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.MinBidSize = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.BidSize = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.MinOfferSize = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.OfferSize = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.ValidUntilTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myQuoteResponse_RegexValidator.BidSpotRate = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.OfferSpotRate = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.BidForwardPoints = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.OfferForwardPoints = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.MidPx = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.BidYield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.MidYield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.OfferYield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.TransactTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myQuoteResponse_RegexValidator.OrdType = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.BidForwardPoints2 = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.OfferForwardPoints2 = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.SettlCurrBidFxRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.SettlCurrOfferFxRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.SettlCurrFxRateCalc = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.Commission = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.CommType = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.CustOrderCapacity = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.ExDestination = regexp.MustCompile(`[A-Z0-9]{4}`)
    myQuoteResponse_RegexValidator.Text = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.EncodedTextLen = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.EncodedText = regexp.MustCompile(`.*`)
    myQuoteResponse_RegexValidator.Price = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.PriceType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.Spread = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.BenchmarkCurveCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myQuoteResponse_RegexValidator.BenchmarkCurveName = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.BenchmarkCurvePoint = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.BenchmarkPrice = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.BenchmarkPriceType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.BenchmarkSecurityID = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.BenchmarkSecurityIDSource = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.YieldType = regexp.MustCompile(`[^|]*`)
    myQuoteResponse_RegexValidator.Yield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuoteResponse_RegexValidator.YieldCalcDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.YieldRedemptionDate = regexp.MustCompile(`[0-9]{8}`)
    myQuoteResponse_RegexValidator.YieldRedemptionPrice = regexp.MustCompile(``)
    myQuoteResponse_RegexValidator.YieldRedemptionPriceType = regexp.MustCompile(`-?\d+`)
    myQuoteResponse_RegexValidator.ExDestinationIDSource = regexp.MustCompile(`[^|]`)
    myQuoteResponse_RegexValidator.SignatureLength = regexp.MustCompile(`\d+`)
    myQuoteResponse_RegexValidator.Signature = regexp.MustCompile(`.*`)
    myQuoteResponse_RegexValidator.CheckSum = regexp.MustCompile(`[^|]*`)
}



func (m *QuoteResponse) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.BeginString.HasValue()
    
    
    
    valid = valid && m.BodyLength.HasValue()
    
    
    
    valid = valid && m.MsgType.HasValue()
    
    
    
    valid = valid && m.SenderCompID.HasValue()
    
    
    
    valid = valid && m.TargetCompID.HasValue()
    
    
    
    valid = valid && m.MsgSeqNum.HasValue()
    
    
    
    valid = valid && m.SendingTime.HasValue()
    
    
    
    for _, g := range(m.Hops) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.QuoteRespID.HasValue()
    
    
    
    valid = valid && m.QuoteRespType.HasValue()
    
    
    
    for _, g := range(m.QuoteQualifiers) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.PartyIDs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.SecurityAltID) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Events) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.InstrumentParties) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Underlyings) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Stipulations) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Legs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.CheckSum.HasValue()
    
    
    
    
    
    return valid
}




