package QuotEntryGrp_QuoteEntries

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import SecAltIDGrp_SecurityAltID "grgrbll/fix/Shared/SecAltIDGrp_SecurityAltID"

import EvntGrp_Events "grgrbll/fix/Shared/EvntGrp_Events"

import InstrumentParties_InstrumentParties "grgrbll/fix/Shared/InstrumentParties_InstrumentParties"

import InstrmtLegGrp_Legs "grgrbll/fix/Shared/InstrmtLegGrp_Legs"


type quotEntryGrp_QuoteEntries_RegexValidator struct {
    QuoteEntryID *(regexp.Regexp)
    Symbol *(regexp.Regexp)
    SymbolSfx *(regexp.Regexp)
    SecurityID *(regexp.Regexp)
    SecurityIDSource *(regexp.Regexp)
    Product *(regexp.Regexp)
    CFICode *(regexp.Regexp)
    SecurityType *(regexp.Regexp)
    SecuritySubType *(regexp.Regexp)
    MaturityMonthYear *(regexp.Regexp)
    MaturityDate *(regexp.Regexp)
    CouponPaymentDate *(regexp.Regexp)
    IssueDate *(regexp.Regexp)
    RepoCollateralSecurityType *(regexp.Regexp)
    RepurchaseTerm *(regexp.Regexp)
    RepurchaseRate *(regexp.Regexp)
    Factor *(regexp.Regexp)
    CreditRating *(regexp.Regexp)
    InstrRegistry *(regexp.Regexp)
    CountryOfIssue *(regexp.Regexp)
    StateOrProvinceOfIssue *(regexp.Regexp)
    LocaleOfIssue *(regexp.Regexp)
    RedemptionDate *(regexp.Regexp)
    StrikePrice *(regexp.Regexp)
    StrikeCurrency *(regexp.Regexp)
    OptAttribute *(regexp.Regexp)
    ContractMultiplier *(regexp.Regexp)
    CouponRate *(regexp.Regexp)
    SecurityExchange *(regexp.Regexp)
    Issuer *(regexp.Regexp)
    EncodedIssuerLen *(regexp.Regexp)
    EncodedIssuer *(regexp.Regexp)
    SecurityDesc *(regexp.Regexp)
    EncodedSecurityDescLen *(regexp.Regexp)
    EncodedSecurityDesc *(regexp.Regexp)
    Pool *(regexp.Regexp)
    ContractSettlMonth *(regexp.Regexp)
    CPProgram *(regexp.Regexp)
    CPRegType *(regexp.Regexp)
    DatedDate *(regexp.Regexp)
    InterestAccrualDate *(regexp.Regexp)
    SecurityStatus *(regexp.Regexp)
    SettleOnOpenFlag *(regexp.Regexp)
    InstrmtAssignmentMethod *(regexp.Regexp)
    StrikeMultiplier *(regexp.Regexp)
    StrikeValue *(regexp.Regexp)
    MinPriceIncrement *(regexp.Regexp)
    PositionLimit *(regexp.Regexp)
    NTPositionLimit *(regexp.Regexp)
    UnitofMeasure *(regexp.Regexp)
    TimeUnit *(regexp.Regexp)
    MaturityTime *(regexp.Regexp)
    BidPx *(regexp.Regexp)
    OfferPx *(regexp.Regexp)
    BidSize *(regexp.Regexp)
    OfferSize *(regexp.Regexp)
    ValidUntilTime *(regexp.Regexp)
    BidSpotRate *(regexp.Regexp)
    OfferSpotRate *(regexp.Regexp)
    BidForwardPoints *(regexp.Regexp)
    OfferForwardPoints *(regexp.Regexp)
    MidPx *(regexp.Regexp)
    BidYield *(regexp.Regexp)
    MidYield *(regexp.Regexp)
    OfferYield *(regexp.Regexp)
    TransactTime *(regexp.Regexp)
    TradingSessionID *(regexp.Regexp)
    TradingSessionSubID *(regexp.Regexp)
    SettlDate *(regexp.Regexp)
    OrdType *(regexp.Regexp)
    SettlDate2 *(regexp.Regexp)
    OrderQty2 *(regexp.Regexp)
    BidForwardPoints2 *(regexp.Regexp)
    OfferForwardPoints2 *(regexp.Regexp)
    Currency *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myQuotEntryGrp_QuoteEntries_RegexValidator quotEntryGrp_QuoteEntries_RegexValidator

func init() {
    myQuotEntryGrp_QuoteEntries_RegexValidator
    myQuotEntryGrp_QuoteEntries_RegexValidator.QuoteEntryID = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.Symbol = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SymbolSfx = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SecurityID = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SecurityIDSource = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.Product = regexp.MustCompile(`-?\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.CFICode = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SecurityType = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SecuritySubType = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.MaturityMonthYear = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.MaturityDate = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.CouponPaymentDate = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.IssueDate = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.RepoCollateralSecurityType = regexp.MustCompile(`-?\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.RepurchaseTerm = regexp.MustCompile(`-?\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.RepurchaseRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.Factor = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.CreditRating = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.InstrRegistry = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.CountryOfIssue = regexp.MustCompile(`[A-Z]{2}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.StateOrProvinceOfIssue = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.LocaleOfIssue = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.RedemptionDate = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.StrikePrice = regexp.MustCompile(``)
    myQuotEntryGrp_QuoteEntries_RegexValidator.StrikeCurrency = regexp.MustCompile(`[A-Z]{3}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OptAttribute = regexp.MustCompile(`[^|]`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.ContractMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.CouponRate = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SecurityExchange = regexp.MustCompile(`[A-Z0-9]{4}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.Issuer = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.EncodedIssuerLen = regexp.MustCompile(`\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.EncodedIssuer = regexp.MustCompile(`.*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SecurityDesc = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.EncodedSecurityDescLen = regexp.MustCompile(`\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.EncodedSecurityDesc = regexp.MustCompile(`.*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.Pool = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.ContractSettlMonth = regexp.MustCompile(`[0-9]{6}([0-9]{2}|w[0-9])?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.CPProgram = regexp.MustCompile(`-?\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.CPRegType = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.DatedDate = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.InterestAccrualDate = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SecurityStatus = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SettleOnOpenFlag = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.InstrmtAssignmentMethod = regexp.MustCompile(`[^|]`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.StrikeMultiplier = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.StrikeValue = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.MinPriceIncrement = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.PositionLimit = regexp.MustCompile(`-?\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.NTPositionLimit = regexp.MustCompile(`-?\d+`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.UnitofMeasure = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.TimeUnit = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.MaturityTime = regexp.MustCompile(`\d{2}:\d{2}(:\d{2})?(Z|[\+-]\d{2}(:\d{2})?)`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.BidPx = regexp.MustCompile(``)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OfferPx = regexp.MustCompile(``)
    myQuotEntryGrp_QuoteEntries_RegexValidator.BidSize = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OfferSize = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.ValidUntilTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.BidSpotRate = regexp.MustCompile(``)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OfferSpotRate = regexp.MustCompile(``)
    myQuotEntryGrp_QuoteEntries_RegexValidator.BidForwardPoints = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OfferForwardPoints = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.MidPx = regexp.MustCompile(``)
    myQuotEntryGrp_QuoteEntries_RegexValidator.BidYield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.MidYield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OfferYield = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.TransactTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.TradingSessionID = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.TradingSessionSubID = regexp.MustCompile(`[^|]*`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SettlDate = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OrdType = regexp.MustCompile(`[^|]`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.SettlDate2 = regexp.MustCompile(`[0-9]{8}`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OrderQty2 = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.BidForwardPoints2 = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.OfferForwardPoints2 = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myQuotEntryGrp_QuoteEntries_RegexValidator.Currency = regexp.MustCompile(`[A-Z]{3}`)
}



func (m *QuotEntryGrp_QuoteEntries) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.QuoteEntryID.HasValue()
    
    
    
    for _, g := range(m.SecurityAltID) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Events) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.InstrumentParties) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Legs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    
    
    return valid
}




