package QuotQualGrp_QuoteQualifiers

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit




type QuotQualGrp_QuoteQualifiers struct {
    QuoteQualifier Types.Char `id:"695", required:"N" `
    _controlBlock fixMessageControlBlock
}
