package ListStrikePrice

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import HopGrp_Hops "grgrbll/fix/Shared/HopGrp_Hops"

import InstrmtStrkPxGrp_Strikes "grgrbll/fix/Shared/InstrmtStrkPxGrp_Strikes"

import UndInstrmtStrkPxGrp_Underlyings "grgrbll/fix/Shared/UndInstrmtStrkPxGrp_Underlyings"


type listStrikePrice_RegexValidator struct {
    BeginString *(regexp.Regexp)
    BodyLength *(regexp.Regexp)
    MsgType *(regexp.Regexp)
    SenderCompID *(regexp.Regexp)
    TargetCompID *(regexp.Regexp)
    OnBehalfOfCompID *(regexp.Regexp)
    DeliverToCompID *(regexp.Regexp)
    SecureDataLen *(regexp.Regexp)
    SecureData *(regexp.Regexp)
    MsgSeqNum *(regexp.Regexp)
    SenderSubID *(regexp.Regexp)
    SenderLocationID *(regexp.Regexp)
    TargetSubID *(regexp.Regexp)
    TargetLocationID *(regexp.Regexp)
    OnBehalfOfSubID *(regexp.Regexp)
    OnBehalfOfLocationID *(regexp.Regexp)
    DeliverToSubID *(regexp.Regexp)
    DeliverToLocationID *(regexp.Regexp)
    PossDupFlag *(regexp.Regexp)
    PossResend *(regexp.Regexp)
    SendingTime *(regexp.Regexp)
    OrigSendingTime *(regexp.Regexp)
    XmlDataLen *(regexp.Regexp)
    XmlData *(regexp.Regexp)
    MessageEncoding *(regexp.Regexp)
    LastMsgSeqNumProcessed *(regexp.Regexp)
    ApplVerID *(regexp.Regexp)
    CstmApplVerID *(regexp.Regexp)
    ListID *(regexp.Regexp)
    TotNoStrikes *(regexp.Regexp)
    LastFragment *(regexp.Regexp)
    SignatureLength *(regexp.Regexp)
    Signature *(regexp.Regexp)
    CheckSum *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myListStrikePrice_RegexValidator listStrikePrice_RegexValidator

func init() {
    myListStrikePrice_RegexValidator
    myListStrikePrice_RegexValidator.BeginString = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.BodyLength = regexp.MustCompile(`\d+`)
    myListStrikePrice_RegexValidator.MsgType = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.SenderCompID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.TargetCompID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.OnBehalfOfCompID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.DeliverToCompID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.SecureDataLen = regexp.MustCompile(`\d+`)
    myListStrikePrice_RegexValidator.SecureData = regexp.MustCompile(`.*`)
    myListStrikePrice_RegexValidator.MsgSeqNum = regexp.MustCompile(`\d+`)
    myListStrikePrice_RegexValidator.SenderSubID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.SenderLocationID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.TargetSubID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.TargetLocationID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.OnBehalfOfSubID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.OnBehalfOfLocationID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.DeliverToSubID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.DeliverToLocationID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.PossDupFlag = regexp.MustCompile(`[YN]`)
    myListStrikePrice_RegexValidator.PossResend = regexp.MustCompile(`[YN]`)
    myListStrikePrice_RegexValidator.SendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myListStrikePrice_RegexValidator.OrigSendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myListStrikePrice_RegexValidator.XmlDataLen = regexp.MustCompile(`\d+`)
    myListStrikePrice_RegexValidator.XmlData = regexp.MustCompile(`.*`)
    myListStrikePrice_RegexValidator.MessageEncoding = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.LastMsgSeqNumProcessed = regexp.MustCompile(`\d+`)
    myListStrikePrice_RegexValidator.ApplVerID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.CstmApplVerID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.ListID = regexp.MustCompile(`[^|]*`)
    myListStrikePrice_RegexValidator.TotNoStrikes = regexp.MustCompile(`-?\d+`)
    myListStrikePrice_RegexValidator.LastFragment = regexp.MustCompile(`[YN]`)
    myListStrikePrice_RegexValidator.SignatureLength = regexp.MustCompile(`\d+`)
    myListStrikePrice_RegexValidator.Signature = regexp.MustCompile(`.*`)
    myListStrikePrice_RegexValidator.CheckSum = regexp.MustCompile(`[^|]*`)
}



func (m *ListStrikePrice) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.BeginString.HasValue()
    
    
    
    valid = valid && m.BodyLength.HasValue()
    
    
    
    valid = valid && m.MsgType.HasValue()
    
    
    
    valid = valid && m.SenderCompID.HasValue()
    
    
    
    valid = valid && m.TargetCompID.HasValue()
    
    
    
    valid = valid && m.MsgSeqNum.HasValue()
    
    
    
    valid = valid && m.SendingTime.HasValue()
    
    
    
    for _, g := range(m.Hops) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.ListID.HasValue()
    
    
    
    valid = valid && m.TotNoStrikes.HasValue()
    
    
    
    for _, g := range(m.Strikes) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.Underlyings) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.CheckSum.HasValue()
    
    
    
    
    
    return valid
}




