package RgstDistInstGrp_DistribInsts

import "bufio"
import "regexp"

// Autogenerated at , do not edit




type rgstDistInstGrp_DistribInsts_RegexValidator struct {
    DistribPaymentMethod *(regexp.Regexp)
    DistribPercentage *(regexp.Regexp)
    CashDistribCurr *(regexp.Regexp)
    CashDistribAgentName *(regexp.Regexp)
    CashDistribAgentCode *(regexp.Regexp)
    CashDistribAgentAcctNumber *(regexp.Regexp)
    CashDistribPayRef *(regexp.Regexp)
    CashDistribAgentAcctName *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myRgstDistInstGrp_DistribInsts_RegexValidator rgstDistInstGrp_DistribInsts_RegexValidator

func init() {
    myRgstDistInstGrp_DistribInsts_RegexValidator
    myRgstDistInstGrp_DistribInsts_RegexValidator.DistribPaymentMethod = regexp.MustCompile(`-?\d+`)
    myRgstDistInstGrp_DistribInsts_RegexValidator.DistribPercentage = regexp.MustCompile(`-?\d*(\.\d*)?`)
    myRgstDistInstGrp_DistribInsts_RegexValidator.CashDistribCurr = regexp.MustCompile(`[A-Z]{3}`)
    myRgstDistInstGrp_DistribInsts_RegexValidator.CashDistribAgentName = regexp.MustCompile(`[^|]*`)
    myRgstDistInstGrp_DistribInsts_RegexValidator.CashDistribAgentCode = regexp.MustCompile(`[^|]*`)
    myRgstDistInstGrp_DistribInsts_RegexValidator.CashDistribAgentAcctNumber = regexp.MustCompile(`[^|]*`)
    myRgstDistInstGrp_DistribInsts_RegexValidator.CashDistribPayRef = regexp.MustCompile(`[^|]*`)
    myRgstDistInstGrp_DistribInsts_RegexValidator.CashDistribAgentAcctName = regexp.MustCompile(`[^|]*`)
}



func (m *RgstDistInstGrp_DistribInsts) HasRequiredFields() bool {
    valid := true
    
    

    
    
    
    
    return valid
}




