package LegStipulations_LegStipulations

import "bufio"
import "regexp"

// Autogenerated at , do not edit




type legStipulations_LegStipulations_RegexValidator struct {
    LegStipulationType *(regexp.Regexp)
    LegStipulationValue *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myLegStipulations_LegStipulations_RegexValidator legStipulations_LegStipulations_RegexValidator

func init() {
    myLegStipulations_LegStipulations_RegexValidator
    myLegStipulations_LegStipulations_RegexValidator.LegStipulationType = regexp.MustCompile(`[^|]*`)
    myLegStipulations_LegStipulations_RegexValidator.LegStipulationValue = regexp.MustCompile(`[^|]*`)
}



func (m *LegStipulations_LegStipulations) HasRequiredFields() bool {
    valid := true
    
    

    
    
    
    
    return valid
}




