package AllocationInstructionAck

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import HopGrp_Hops "grgrbll/fix/Shared/HopGrp_Hops"

import Parties_PartyIDs "grgrbll/fix/Shared/Parties_PartyIDs"

import AllocAckGrp_Allocs "grgrbll/fix/Shared/AllocAckGrp_Allocs"


type allocationInstructionAck_RegexValidator struct {
    BeginString *(regexp.Regexp)
    BodyLength *(regexp.Regexp)
    MsgType *(regexp.Regexp)
    SenderCompID *(regexp.Regexp)
    TargetCompID *(regexp.Regexp)
    OnBehalfOfCompID *(regexp.Regexp)
    DeliverToCompID *(regexp.Regexp)
    SecureDataLen *(regexp.Regexp)
    SecureData *(regexp.Regexp)
    MsgSeqNum *(regexp.Regexp)
    SenderSubID *(regexp.Regexp)
    SenderLocationID *(regexp.Regexp)
    TargetSubID *(regexp.Regexp)
    TargetLocationID *(regexp.Regexp)
    OnBehalfOfSubID *(regexp.Regexp)
    OnBehalfOfLocationID *(regexp.Regexp)
    DeliverToSubID *(regexp.Regexp)
    DeliverToLocationID *(regexp.Regexp)
    PossDupFlag *(regexp.Regexp)
    PossResend *(regexp.Regexp)
    SendingTime *(regexp.Regexp)
    OrigSendingTime *(regexp.Regexp)
    XmlDataLen *(regexp.Regexp)
    XmlData *(regexp.Regexp)
    MessageEncoding *(regexp.Regexp)
    LastMsgSeqNumProcessed *(regexp.Regexp)
    ApplVerID *(regexp.Regexp)
    CstmApplVerID *(regexp.Regexp)
    AllocID *(regexp.Regexp)
    SecondaryAllocID *(regexp.Regexp)
    TradeDate *(regexp.Regexp)
    TransactTime *(regexp.Regexp)
    AllocStatus *(regexp.Regexp)
    AllocRejCode *(regexp.Regexp)
    AllocType *(regexp.Regexp)
    AllocIntermedReqType *(regexp.Regexp)
    MatchStatus *(regexp.Regexp)
    Product *(regexp.Regexp)
    SecurityType *(regexp.Regexp)
    Text *(regexp.Regexp)
    EncodedTextLen *(regexp.Regexp)
    EncodedText *(regexp.Regexp)
    SignatureLength *(regexp.Regexp)
    Signature *(regexp.Regexp)
    CheckSum *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myAllocationInstructionAck_RegexValidator allocationInstructionAck_RegexValidator

func init() {
    myAllocationInstructionAck_RegexValidator
    myAllocationInstructionAck_RegexValidator.BeginString = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.BodyLength = regexp.MustCompile(`\d+`)
    myAllocationInstructionAck_RegexValidator.MsgType = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.SenderCompID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.TargetCompID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.OnBehalfOfCompID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.DeliverToCompID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.SecureDataLen = regexp.MustCompile(`\d+`)
    myAllocationInstructionAck_RegexValidator.SecureData = regexp.MustCompile(`.*`)
    myAllocationInstructionAck_RegexValidator.MsgSeqNum = regexp.MustCompile(`\d+`)
    myAllocationInstructionAck_RegexValidator.SenderSubID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.SenderLocationID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.TargetSubID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.TargetLocationID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.OnBehalfOfSubID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.OnBehalfOfLocationID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.DeliverToSubID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.DeliverToLocationID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.PossDupFlag = regexp.MustCompile(`[YN]`)
    myAllocationInstructionAck_RegexValidator.PossResend = regexp.MustCompile(`[YN]`)
    myAllocationInstructionAck_RegexValidator.SendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myAllocationInstructionAck_RegexValidator.OrigSendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myAllocationInstructionAck_RegexValidator.XmlDataLen = regexp.MustCompile(`\d+`)
    myAllocationInstructionAck_RegexValidator.XmlData = regexp.MustCompile(`.*`)
    myAllocationInstructionAck_RegexValidator.MessageEncoding = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.LastMsgSeqNumProcessed = regexp.MustCompile(`\d+`)
    myAllocationInstructionAck_RegexValidator.ApplVerID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.CstmApplVerID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.AllocID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.SecondaryAllocID = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.TradeDate = regexp.MustCompile(`[0-9]{8}`)
    myAllocationInstructionAck_RegexValidator.TransactTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myAllocationInstructionAck_RegexValidator.AllocStatus = regexp.MustCompile(`-?\d+`)
    myAllocationInstructionAck_RegexValidator.AllocRejCode = regexp.MustCompile(`-?\d+`)
    myAllocationInstructionAck_RegexValidator.AllocType = regexp.MustCompile(`-?\d+`)
    myAllocationInstructionAck_RegexValidator.AllocIntermedReqType = regexp.MustCompile(`-?\d+`)
    myAllocationInstructionAck_RegexValidator.MatchStatus = regexp.MustCompile(`[^|]`)
    myAllocationInstructionAck_RegexValidator.Product = regexp.MustCompile(`-?\d+`)
    myAllocationInstructionAck_RegexValidator.SecurityType = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.Text = regexp.MustCompile(`[^|]*`)
    myAllocationInstructionAck_RegexValidator.EncodedTextLen = regexp.MustCompile(`\d+`)
    myAllocationInstructionAck_RegexValidator.EncodedText = regexp.MustCompile(`.*`)
    myAllocationInstructionAck_RegexValidator.SignatureLength = regexp.MustCompile(`\d+`)
    myAllocationInstructionAck_RegexValidator.Signature = regexp.MustCompile(`.*`)
    myAllocationInstructionAck_RegexValidator.CheckSum = regexp.MustCompile(`[^|]*`)
}



func (m *AllocationInstructionAck) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.BeginString.HasValue()
    
    
    
    valid = valid && m.BodyLength.HasValue()
    
    
    
    valid = valid && m.MsgType.HasValue()
    
    
    
    valid = valid && m.SenderCompID.HasValue()
    
    
    
    valid = valid && m.TargetCompID.HasValue()
    
    
    
    valid = valid && m.MsgSeqNum.HasValue()
    
    
    
    valid = valid && m.SendingTime.HasValue()
    
    
    
    for _, g := range(m.Hops) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.AllocID.HasValue()
    
    
    
    for _, g := range(m.PartyIDs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.AllocStatus.HasValue()
    
    
    
    for _, g := range(m.Allocs) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.CheckSum.HasValue()
    
    
    
    
    
    return valid
}




