package TrdAllocGrp_Allocs

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit



import NestedParties2_Nested2PartyIDs "grgrbll/fix/Shared/NestedParties2_Nested2PartyIDs"


type TrdAllocGrp_Allocs struct {
    AllocAccount Types.String `id:"79", required:"N" `
    AllocAcctIDSource Types.Int `id:"661", required:"N" `
    AllocSettlCurrency Types.Currency `id:"736", required:"N" `
    IndividualAllocID Types.String `id:"467", required:"N" `
    Nested2PartyIDs []NestedParties2_Nested2PartyIDs.NestedParties2_Nested2PartyIDs `counter_name:"NoNested2PartyIDs", counter_id:"756"`
    AllocQty Types.Qty `id:"80", required:"N" `
    AllocCustomerCapacity Types.String `id:"993", required:"N" `
    AllocMethod Types.Int `id:"1002", required:"N" `
    SecondaryIndividualAllocID Types.String `id:"989", required:"N" `
    AllocClearingFeeIndicator Types.String `id:"1136", required:"N" `
    _controlBlock fixMessageControlBlock
}
