package MarketDataRequest

import "bufio"
import "grgrbll/Fix/FixDef/Types"
import "regexp"

// Autogenerated at , do not edit



import HopGrp_Hops "grgrbll/fix/Shared/HopGrp_Hops"

import MDReqGrp_MDEntryTypes "grgrbll/fix/Shared/MDReqGrp_MDEntryTypes"

import InstrmtMDReqGrp_RelatedSym "grgrbll/fix/Shared/InstrmtMDReqGrp_RelatedSym"

import TrdgSesGrp_TradingSessions "grgrbll/fix/Shared/TrdgSesGrp_TradingSessions"


type marketDataRequest_RegexValidator struct {
    BeginString *(regexp.Regexp)
    BodyLength *(regexp.Regexp)
    MsgType *(regexp.Regexp)
    SenderCompID *(regexp.Regexp)
    TargetCompID *(regexp.Regexp)
    OnBehalfOfCompID *(regexp.Regexp)
    DeliverToCompID *(regexp.Regexp)
    SecureDataLen *(regexp.Regexp)
    SecureData *(regexp.Regexp)
    MsgSeqNum *(regexp.Regexp)
    SenderSubID *(regexp.Regexp)
    SenderLocationID *(regexp.Regexp)
    TargetSubID *(regexp.Regexp)
    TargetLocationID *(regexp.Regexp)
    OnBehalfOfSubID *(regexp.Regexp)
    OnBehalfOfLocationID *(regexp.Regexp)
    DeliverToSubID *(regexp.Regexp)
    DeliverToLocationID *(regexp.Regexp)
    PossDupFlag *(regexp.Regexp)
    PossResend *(regexp.Regexp)
    SendingTime *(regexp.Regexp)
    OrigSendingTime *(regexp.Regexp)
    XmlDataLen *(regexp.Regexp)
    XmlData *(regexp.Regexp)
    MessageEncoding *(regexp.Regexp)
    LastMsgSeqNumProcessed *(regexp.Regexp)
    ApplVerID *(regexp.Regexp)
    CstmApplVerID *(regexp.Regexp)
    MDReqID *(regexp.Regexp)
    SubscriptionRequestType *(regexp.Regexp)
    MarketDepth *(regexp.Regexp)
    MDUpdateType *(regexp.Regexp)
    AggregatedBook *(regexp.Regexp)
    OpenCloseSettlFlag *(regexp.Regexp)
    Scope *(regexp.Regexp)
    MDImplicitDelete *(regexp.Regexp)
    ApplQueueAction *(regexp.Regexp)
    ApplQueueMax *(regexp.Regexp)
    MDQuoteType *(regexp.Regexp)
    SignatureLength *(regexp.Regexp)
    Signature *(regexp.Regexp)
    CheckSum *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myMarketDataRequest_RegexValidator marketDataRequest_RegexValidator

func init() {
    myMarketDataRequest_RegexValidator
    myMarketDataRequest_RegexValidator.BeginString = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.BodyLength = regexp.MustCompile(`\d+`)
    myMarketDataRequest_RegexValidator.MsgType = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.SenderCompID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.TargetCompID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.OnBehalfOfCompID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.DeliverToCompID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.SecureDataLen = regexp.MustCompile(`\d+`)
    myMarketDataRequest_RegexValidator.SecureData = regexp.MustCompile(`.*`)
    myMarketDataRequest_RegexValidator.MsgSeqNum = regexp.MustCompile(`\d+`)
    myMarketDataRequest_RegexValidator.SenderSubID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.SenderLocationID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.TargetSubID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.TargetLocationID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.OnBehalfOfSubID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.OnBehalfOfLocationID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.DeliverToSubID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.DeliverToLocationID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.PossDupFlag = regexp.MustCompile(`[YN]`)
    myMarketDataRequest_RegexValidator.PossResend = regexp.MustCompile(`[YN]`)
    myMarketDataRequest_RegexValidator.SendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myMarketDataRequest_RegexValidator.OrigSendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myMarketDataRequest_RegexValidator.XmlDataLen = regexp.MustCompile(`\d+`)
    myMarketDataRequest_RegexValidator.XmlData = regexp.MustCompile(`.*`)
    myMarketDataRequest_RegexValidator.MessageEncoding = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.LastMsgSeqNumProcessed = regexp.MustCompile(`\d+`)
    myMarketDataRequest_RegexValidator.ApplVerID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.CstmApplVerID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.MDReqID = regexp.MustCompile(`[^|]*`)
    myMarketDataRequest_RegexValidator.SubscriptionRequestType = regexp.MustCompile(`[^|]`)
    myMarketDataRequest_RegexValidator.MarketDepth = regexp.MustCompile(`-?\d+`)
    myMarketDataRequest_RegexValidator.MDUpdateType = regexp.MustCompile(`-?\d+`)
    myMarketDataRequest_RegexValidator.AggregatedBook = regexp.MustCompile(`[YN]`)
    myMarketDataRequest_RegexValidator.OpenCloseSettlFlag = regexp.MustCompile(`[ ]?(\w[ ])+\w?`)
    myMarketDataRequest_RegexValidator.Scope = regexp.MustCompile(`[ ]?(\w[ ])+\w?`)
    myMarketDataRequest_RegexValidator.MDImplicitDelete = regexp.MustCompile(`[YN]`)
    myMarketDataRequest_RegexValidator.ApplQueueAction = regexp.MustCompile(`-?\d+`)
    myMarketDataRequest_RegexValidator.ApplQueueMax = regexp.MustCompile(`-?\d+`)
    myMarketDataRequest_RegexValidator.MDQuoteType = regexp.MustCompile(`-?\d+`)
    myMarketDataRequest_RegexValidator.SignatureLength = regexp.MustCompile(`\d+`)
    myMarketDataRequest_RegexValidator.Signature = regexp.MustCompile(`.*`)
    myMarketDataRequest_RegexValidator.CheckSum = regexp.MustCompile(`[^|]*`)
}



func (m *MarketDataRequest) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.BeginString.HasValue()
    
    
    
    valid = valid && m.BodyLength.HasValue()
    
    
    
    valid = valid && m.MsgType.HasValue()
    
    
    
    valid = valid && m.SenderCompID.HasValue()
    
    
    
    valid = valid && m.TargetCompID.HasValue()
    
    
    
    valid = valid && m.MsgSeqNum.HasValue()
    
    
    
    valid = valid && m.SendingTime.HasValue()
    
    
    
    for _, g := range(m.Hops) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.MDReqID.HasValue()
    
    
    
    valid = valid && m.SubscriptionRequestType.HasValue()
    
    
    
    valid = valid && m.MarketDepth.HasValue()
    
    
    
    for _, g := range(m.MDEntryTypes) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.RelatedSym) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    for _, g := range(m.TradingSessions) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.CheckSum.HasValue()
    
    
    
    
    
    return valid
}




