package TradeCaptureReportRequest_Dates

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit




type TradeCaptureReportRequest_Dates struct {
    TradeDate Types.LocalMktDate `id:"75", required:"N" `
    LastUpdateTime Types.UTCTimestamp `id:"779", required:"N" `
    TransactTime Types.UTCTimestamp `id:"60", required:"N" `
    _controlBlock fixMessageControlBlock
}
