package SideCrossOrdModGrp_Sides

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit



import Parties_PartyIDs "grgrbll/fix/Shared/Parties_PartyIDs"

import PreAllocGrp_Allocs "grgrbll/fix/Shared/PreAllocGrp_Allocs"


type SideCrossOrdModGrp_Sides struct {
    Side Types.Char `id:"54", required:"Y" `
    ClOrdID Types.String `id:"11", required:"Y" `
    SecondaryClOrdID Types.String `id:"526", required:"N" `
    ClOrdLinkID Types.String `id:"583", required:"N" `
    PartyIDs []Parties_PartyIDs.Parties_PartyIDs `counter_name:"NoPartyIDs", counter_id:"453"`
    TradeOriginationDate Types.LocalMktDate `id:"229", required:"N" `
    TradeDate Types.LocalMktDate `id:"75", required:"N" `
    Account Types.String `id:"1", required:"N" `
    AcctIDSource Types.Int `id:"660", required:"N" `
    AccountType Types.Int `id:"581", required:"N" `
    DayBookingInst Types.Char `id:"589", required:"N" `
    BookingUnit Types.Char `id:"590", required:"N" `
    PreallocMethod Types.Char `id:"591", required:"N" `
    AllocID Types.String `id:"70", required:"N" `
    Allocs []PreAllocGrp_Allocs.PreAllocGrp_Allocs `counter_name:"NoAllocs", counter_id:"78"`
    QtyType Types.Int `id:"854", required:"N" `
    OrderQty Types.Qty `id:"38", required:"N" `
    CashOrderQty Types.Qty `id:"152", required:"N" `
    OrderPercent Types.Percentage `id:"516", required:"N" `
    RoundingDirection Types.Char `id:"468", required:"N" `
    RoundingModulus Types.Float `id:"469", required:"N" `
    Commission Types.Amt `id:"12", required:"N" `
    CommType Types.Char `id:"13", required:"N" `
    CommCurrency Types.Currency `id:"479", required:"N" `
    FundRenewWaiv Types.Char `id:"497", required:"N" `
    OrderCapacity Types.Char `id:"528", required:"N" `
    OrderRestrictions Types.MultipleCharValue `id:"529", required:"N" `
    CustOrderCapacity Types.Int `id:"582", required:"N" `
    ForexReq Types.Boolean `id:"121", required:"N" `
    SettlCurrency Types.Currency `id:"120", required:"N" `
    BookingType Types.Int `id:"775", required:"N" `
    Text Types.String `id:"58", required:"N" `
    EncodedTextLen Types.Length `id:"354", required:"N" `
    EncodedText Types.Data `id:"355", required:"N" `
    PositionEffect Types.Char `id:"77", required:"N" `
    CoveredOrUncovered Types.Int `id:"203", required:"N" `
    CashMargin Types.Char `id:"544", required:"N" `
    ClearingFeeIndicator Types.String `id:"635", required:"N" `
    SolicitedFlag Types.Boolean `id:"377", required:"N" `
    SideComplianceID Types.String `id:"659", required:"N" `
    SideTimeInForce Types.UTCTimestamp `id:"962", required:"N" `
    PreTradeAnonymity Types.Boolean `id:"1091", required:"N" `
    _controlBlock fixMessageControlBlock
}
