package AffectedOrdGrp_AffectedOrders

import "bufio"
import "regexp"

// Autogenerated at , do not edit




type affectedOrdGrp_AffectedOrders_RegexValidator struct {
    OrigClOrdID *(regexp.Regexp)
    AffectedOrderID *(regexp.Regexp)
    AffectedSecondaryOrderID *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myAffectedOrdGrp_AffectedOrders_RegexValidator affectedOrdGrp_AffectedOrders_RegexValidator

func init() {
    myAffectedOrdGrp_AffectedOrders_RegexValidator
    myAffectedOrdGrp_AffectedOrders_RegexValidator.OrigClOrdID = regexp.MustCompile(`[^|]*`)
    myAffectedOrdGrp_AffectedOrders_RegexValidator.AffectedOrderID = regexp.MustCompile(`[^|]*`)
    myAffectedOrdGrp_AffectedOrders_RegexValidator.AffectedSecondaryOrderID = regexp.MustCompile(`[^|]*`)
}



func (m *AffectedOrdGrp_AffectedOrders) HasRequiredFields() bool {
    valid := true
    
    

    
    
    
    
    return valid
}




