package BusinessMessageReject

import "bufio"
import "regexp"

// Autogenerated at , do not edit



import HopGrp_Hops "grgrbll/fix/Shared/HopGrp_Hops"


type businessMessageReject_RegexValidator struct {
    BeginString *(regexp.Regexp)
    BodyLength *(regexp.Regexp)
    MsgType *(regexp.Regexp)
    SenderCompID *(regexp.Regexp)
    TargetCompID *(regexp.Regexp)
    OnBehalfOfCompID *(regexp.Regexp)
    DeliverToCompID *(regexp.Regexp)
    SecureDataLen *(regexp.Regexp)
    SecureData *(regexp.Regexp)
    MsgSeqNum *(regexp.Regexp)
    SenderSubID *(regexp.Regexp)
    SenderLocationID *(regexp.Regexp)
    TargetSubID *(regexp.Regexp)
    TargetLocationID *(regexp.Regexp)
    OnBehalfOfSubID *(regexp.Regexp)
    OnBehalfOfLocationID *(regexp.Regexp)
    DeliverToSubID *(regexp.Regexp)
    DeliverToLocationID *(regexp.Regexp)
    PossDupFlag *(regexp.Regexp)
    PossResend *(regexp.Regexp)
    SendingTime *(regexp.Regexp)
    OrigSendingTime *(regexp.Regexp)
    XmlDataLen *(regexp.Regexp)
    XmlData *(regexp.Regexp)
    MessageEncoding *(regexp.Regexp)
    LastMsgSeqNumProcessed *(regexp.Regexp)
    ApplVerID *(regexp.Regexp)
    CstmApplVerID *(regexp.Regexp)
    RefSeqNum *(regexp.Regexp)
    RefMsgType *(regexp.Regexp)
    BusinessRejectRefID *(regexp.Regexp)
    BusinessRejectReason *(regexp.Regexp)
    Text *(regexp.Regexp)
    EncodedTextLen *(regexp.Regexp)
    EncodedText *(regexp.Regexp)
    SignatureLength *(regexp.Regexp)
    Signature *(regexp.Regexp)
    CheckSum *(regexp.Regexp)
    _controlBlock fixMessageControlBlock
}


var myBusinessMessageReject_RegexValidator businessMessageReject_RegexValidator

func init() {
    myBusinessMessageReject_RegexValidator
    myBusinessMessageReject_RegexValidator.BeginString = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.BodyLength = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.MsgType = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.SenderCompID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.TargetCompID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.OnBehalfOfCompID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.DeliverToCompID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.SecureDataLen = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.SecureData = regexp.MustCompile(`.*`)
    myBusinessMessageReject_RegexValidator.MsgSeqNum = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.SenderSubID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.SenderLocationID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.TargetSubID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.TargetLocationID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.OnBehalfOfSubID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.OnBehalfOfLocationID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.DeliverToSubID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.DeliverToLocationID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.PossDupFlag = regexp.MustCompile(`[YN]`)
    myBusinessMessageReject_RegexValidator.PossResend = regexp.MustCompile(`[YN]`)
    myBusinessMessageReject_RegexValidator.SendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myBusinessMessageReject_RegexValidator.OrigSendingTime = regexp.MustCompile(`\d{4}(0[1-9]|1[012])(0[1-9]|[12]\d|3[01])-([01][0-9]|2[0-3]):[0-5][0-9]:[0-5][0-9](.\d{3})?`)
    myBusinessMessageReject_RegexValidator.XmlDataLen = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.XmlData = regexp.MustCompile(`.*`)
    myBusinessMessageReject_RegexValidator.MessageEncoding = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.LastMsgSeqNumProcessed = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.ApplVerID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.CstmApplVerID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.RefSeqNum = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.RefMsgType = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.BusinessRejectRefID = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.BusinessRejectReason = regexp.MustCompile(`-?\d+`)
    myBusinessMessageReject_RegexValidator.Text = regexp.MustCompile(`[^|]*`)
    myBusinessMessageReject_RegexValidator.EncodedTextLen = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.EncodedText = regexp.MustCompile(`.*`)
    myBusinessMessageReject_RegexValidator.SignatureLength = regexp.MustCompile(`\d+`)
    myBusinessMessageReject_RegexValidator.Signature = regexp.MustCompile(`.*`)
    myBusinessMessageReject_RegexValidator.CheckSum = regexp.MustCompile(`[^|]*`)
}



func (m *BusinessMessageReject) HasRequiredFields() bool {
    valid := true
    
    

    
    
    valid = valid && m.BeginString.HasValue()
    
    
    
    valid = valid && m.BodyLength.HasValue()
    
    
    
    valid = valid && m.MsgType.HasValue()
    
    
    
    valid = valid && m.SenderCompID.HasValue()
    
    
    
    valid = valid && m.TargetCompID.HasValue()
    
    
    
    valid = valid && m.MsgSeqNum.HasValue()
    
    
    
    valid = valid && m.SendingTime.HasValue()
    
    
    
    for _, g := range(m.Hops) {
        valid = valid && g.HasRequiredFields()
    }
    
    
    
    valid = valid && m.RefMsgType.HasValue()
    
    
    
    valid = valid && m.BusinessRejectReason.HasValue()
    
    
    
    valid = valid && m.CheckSum.HasValue()
    
    
    
    
    
    return valid
}




