package AttrbGrp_InstrAttrib

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit




type AttrbGrp_InstrAttrib struct {
    InstrAttribType Types.Int `id:"871", required:"N" `
    InstrAttribValue Types.String `id:"872", required:"N" `
    _controlBlock fixMessageControlBlock
}
