package OrdListStatGrp_Orders

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit




type OrdListStatGrp_Orders struct {
    ClOrdID Types.String `id:"11", required:"Y" `
    SecondaryClOrdID Types.String `id:"526", required:"N" `
    CumQty Types.Qty `id:"14", required:"Y" `
    OrdStatus Types.Char `id:"39", required:"Y" `
    WorkingIndicator Types.Boolean `id:"636", required:"N" `
    LeavesQty Types.Qty `id:"151", required:"Y" `
    CxlQty Types.Qty `id:"84", required:"Y" `
    AvgPx Types.Price `id:"6", required:"Y" `
    OrdRejReason Types.Int `id:"103", required:"N" `
    Text Types.String `id:"58", required:"N" `
    EncodedTextLen Types.Length `id:"354", required:"N" `
    EncodedText Types.Data `id:"355", required:"N" `
    _controlBlock fixMessageControlBlock
}
