package BidDescReqGrp_BidDescriptors

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit




type BidDescReqGrp_BidDescriptors struct {
    BidDescriptorType Types.Int `id:"399", required:"N" `
    BidDescriptor Types.String `id:"400", required:"N" `
    SideValueInd Types.Int `id:"401", required:"N" `
    LiquidityValue Types.Amt `id:"404", required:"N" `
    LiquidityNumSecurities Types.Int `id:"441", required:"N" `
    LiquidityPctLow Types.Percentage `id:"402", required:"N" `
    LiquidityPctHigh Types.Percentage `id:"403", required:"N" `
    EFPTrackingError Types.Percentage `id:"405", required:"N" `
    FairValue Types.Amt `id:"406", required:"N" `
    OutsideIndexPct Types.Percentage `id:"407", required:"N" `
    ValueOfFutures Types.Amt `id:"408", required:"N" `
    _controlBlock fixMessageControlBlock
}
