package NstdPtysSubGrp_NestedPartySubIDs

import "bufio"
import "grgrbll/Fix/FixDef/Types"

// Autogenerated at , do not edit




type NstdPtysSubGrp_NestedPartySubIDs struct {
    NestedPartySubID Types.String `id:"545", required:"N" `
    NestedPartySubIDType Types.Int `id:"805", required:"N" `
    _controlBlock fixMessageControlBlock
}
